version: "3"
services:
  git-synchronizer:
    build:
      context: ../../
      dockerfile: docker/local/git-synchronizer/Dockerfile
    image: git-synchronizer
    container_name: git-synchronizer
    hostname: git-synchronizer
    dns: 8.8.8.8
    tty: true
    stdin_open: true
    ports:
      - "50000:50000"
    environment:
      - TZ=Asia/Tokyo
      - LANG=ja_JP.utf8
    networks:
      - git-synchronizer
networks:
  git-synchronizer:
